<?php

session_start();

$_SESSION['rrr'] = '<div id= "Civi" class="recka sort">
			<h2>Cywilizacja 3</h2>
			Sid Meier’s Civilization III to wydana na PC Windows trzecia pełnoprawna odsłona popularnej serii turowych gier strategicznych, której pierwsze dwie części ukazały się w latach 1991-95 nakładem firmy Microprose. Za powstanie gry odpowiada założone przez Sida Meiera po odejściu z Microprose studio Firaxis Games. Sam Meier pełnił tu jednak wyłącznie rolę dyrektora kreatywnego, zaś głównymi projektantami trzeciej Cywilizacji byli Jeff Briggs oraz Soren Johnson. <br /> <h3> Mechanika </h3> Podobnie jak w poprzednich odsłonach cyklu, w Civilization III obejmujemy pieczę nad wybraną cywilizacją, a naszym zadaniem jest poprowadzenie jej poprzez kolejne ery rozwoju: począwszy od roku 4000 p.n.e. aż do czasów współczesnych. Do naszych obowiązków należy m.in. systematyczne powiększanie posiadanego terenu, wznoszenie i rozbudowa miast, szkolenie jednostek militarnych oraz osadników, prowadzenie badań nad nowymi technologiami oraz toczenie wojen bądź nawiązywanie stosunków dyplomatycznych z innymi nacjami. Do sukcesu w grze wymagane jest odpowiednie zbalansowanie działań, obejmujących zarządzanie gospodarką, wojskiem oraz rozwojem technologicznym. W zależności od preferencji gracza, do zwycięstwa dojść można różnymi drogami. W Sid Meier’s Civilization III do naszej dyspozycji oddano 16 grywalnych cywilizacji, odznaczających się własną specyfiką. Każda ma też od początku dwie umiejętności, które pozostałe nacje muszą dopiero wynaleźć, a także wyjątkową jednostkę – odpowiednie jej wykorzystanie może przechylić szalę zwycięstwa na naszą stronę. Pod względem mechaniki, tytuł bazuje na dokładnie tych samych założeniach ogólnych co poprzednie odsłony serii. W grze nie obeszło się jednak bez kilku istotnych nowości. W Civilization III zmienił się interfejs – teraz jest znacznie bardziej intuicyjny i zwiększono ilość informacji o miastach dostępnych z poziomu mapy głównej. Dwie najważniejsze zmiany to wprowadzenie dowódców armii, z biegiem rozgrywki gromadzących doświadczenie, a także surowców strategicznych, które występują tylko w określonych miejscach i służą do produkcji konkretnych broni czy technologii. <br /> <h3> Kwestie techniczne </h3> Jako że od premiery drugiej części Cywilizacji upłunęło pięć lat, wydana na PC Windows gra Sid Meier’s Civilization III odznacza się zauważalnie lepszą oprawą graficzną, dostosowaną do ówczesnych standardów. Rozgrywka ukazana została w tradycyjnym rzucie izometrycznym, a mapy – choć wykonane niezwykle starannie – są bardzo czytelne i nieprzeładowane niepotrzebnymi szczegółami. Grafika wykonana została w wyższej rozdzielczości, poprawie uległa też jakość animacji (np. sposób poruszania się jednostek). Całości towarzyszy zaś tradycyjnie profesjonalna i pasująca do klimatu rozgrywki warstwa muzyczna, za którą odpowiada doświadczony amerykański kompozytor i dyrygent Roger Briggs.
			<br /><iframe width="560" height="315" src="https://www.youtube.com/embed/lEmebT7GbPs" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

		</div>';
$_SESSION['ocenka'] = 8;
$_SESSION['dana_gra'] = "Civi";
		
		header('Location:../recka.php?tak=Civi');

?>