<?php

session_start();

$_SESSION['rrr'] = '<div id="Halo" class="recka sort">
			<h2>Halo 3</h2>
			Trzecia odsłona serii o wojnie ludzi z tajemniczą, żyjącą w wydrążonych pod ziemią tunelach armią Locustów. Za stworzenie tej, a także pozostałych części odpowiada ekipa z Epic Games, której twarzą i głównym producentem jest Cliff Bleszinski. Po zniszczeniu i zatopieniu miasta Jacinto, koalicja COG nadal prowadzi walkę z przeważającymi siłami przeciwnika, wśród których nie zabrakło również zupełnie nowych przedstawicieli, jak na przykład olbrzymiego, wyposażonego w macki stwora, zdolnego zadać obrażenia nawet żołnierzom ukrywającym się za osłoną. Para przyjaciół, czyli Marcus Fenix i Dominic Santiago wspólnie z innymi towarzyszami broni wyruszają między innymi na poszukiwanie ojca Marcusa, ponieważ jego odnalezienie najprawdopodobniej pozwoli ludziom zdobyć wiedzę, w jaki sposób raz na zawsze pozbyć się Szarańczy. W sumie kampania dla jednego gracza oferuje 31 misji, w których można znaleźć 57 różnego rodzaju „znajdziek”. Przygodę można przeżyć zarówno solo, jak i w trybie kooperacji, w którym jednocześnie mogą wziąć udział nawet cztery osoby. To znaczący progres w stosunku do poprzednich części gry, gdzie kampanię można było ukończyć tylko samotnie bądź w duecie z drugim graczem. Od pierwszej części seria oferuje emocjonujące pojedynki wieloosobowe i tu jest podobnie. Wśród nowych trybów multiplayer pojawił się Beast Mode będący odpowiednikiem znanej już Hordy, ale w przeciwieństwie do niej, tym razem gracze wcielają się w Locustów. Role więc się odwracają, a naszym celem jest pozbycie się jak największej ilości żołnierzy COG. Zmagania toczymy w nowych lokacjach, takich jak np. Trenches, w której szalejąca burza piaskowa ogranicza widoczność. Pozostałe mapy, to m.in. Overpass, Mercy, Checkout i Trashball. Serii Gears of War udało się wykreować charakterystyczną broń wyposażoną w piłę łańcuchową, czyli karabin Lancer. W części trzeciej otrzymujemy dostęp do jego klasycznej wersji wyposażonej w kilka modyfikacji, ale wśród narzędzi zagłady jest także Retro Lancer, Sawed-off Shotgun, czy ciężki karabin snajperski One Shot, którego pocisk ma zdolność przebijania tarcz przeciwnika i osłon, za którymi się on kryje. Ponadto możemy skorzystać z Incendinary Grenade, Digger Launcher oraz nieco przerobionej wersji popularnego Hammerbursta. Nie zabrakło również ciężkich narzędzi zagłady pokroju szybkostrzelnego działka Vulcan czy też robota bojowego Silverback. Oczywiście każda z broni działa odmiennie, a ponadto przy okazji wykonywania z jej użyciem egzekucji na przeciwniku, jesteśmy świadkami przypisanych im zróżnicowanych animacji. Gra ukazałą się wyłącznie na konsolę xbox 360.
			<iframe width="560" height="315" src="https://www.youtube.com/embed/1nDJQwO7CWg" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
		</div>';
$_SESSION['ocenka'] = 9.3;
$_SESSION['dana_gra'] = "Halo";
		
		header('Location:../recka.php?tak=Halo');

?>